frogohs/apps/vgdb/urls.py
from django.conf.urls.defaults import patterns, include, url

import views

urlpatterns = patterns('',
    
    url(r'^platforms/$', 
#        views.PlatformListView.as_view(),
        views.platform_list_get,
        name='vgdb-platform-list'),
        
    url(r'^platforms/(?P<platform_slug>[\w-]+)/$', 
#        views.PlatformDetailView.as_view(), 
        views.platform_detail_get,
        name='vgdb-platform-detail'),
        
    url(r'^distmethods/$', 
#        views.DistMethodListView.as_view(),
        views.distmethod_list_get,
        name='vgdb-distmethod-list'),
        
    url(r'^distmethods/(?P<distmethod_slug>[\w-]+)/$', 
#        views.DistMethodDetailView.as_view(),
        views.distmethod_detail_get,
        name='vgdb-distmethod-detail'),
        
    url(r'^series/$', 
#        views.SeriesListView.as_view(),
        views.series_list_get,
        name='vgdb-series-list'),
        
    url(r'^series/(?P<series_id>\d+)/$', 
#        views.SeriesDetailView.as_view(),
        views.series_detail_get,
        name='vgdb-series-detail'),

    url(r'^game/(?P<game_id>\d+)/$',
        views.game_detail_get,
        name='vgdb-game-detail'),
)


frogohs/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'frogohs.views.home', name='home'),
    # url(r'^frogohs/', include('frogohs.foo.urls')),
	
    url(r'^project/', include('frogohs.apps.project.urls')),

    url(r'^vgdb/', include('frogohs.apps.vgdb.urls')),
    
    url(r'^collmgt/', include('frogohs.apps.collmgt.urls')),
    
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^accounts/', include('registration.backends.default.urls')),
)

frogohs/apps/vgdb/models.py
from django.db import models
import managers

# Platforms and Distribution Methods
class Platform(models.Model):
    objects = managers.PlatformManager()

    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True)
    
    def natural_key(self):
        return (self.slug,)
    
    def __unicode__(self):
        return self.name
        
    class Meta:
        ordering = ['name']

class DistMethod(models.Model):
    
    objects = managers.DistMethodManager()
    
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True)
    
    def natural_key(self):
        return (self.slug,)
    
    def __unicode__(self):
        return self.name
    
    class Meta:
        ordering = ['name']
        verbose_name = 'distribution method'
        verbose_name_plural = 'distribution methods'

class PlatformDistMethod(models.Model):
    platform = models.ForeignKey(Platform, related_name='dist_method_set')
    dist_method = models.ForeignKey(DistMethod, related_name='platform_set')
    is_transferrable = models.BooleanField()
    
    def __unicode__(self):
        return u"%(platform)s via %(dist_method)s" % {"platform" : self.platform,
                                                      "dist_method" : self.dist_method,}
    
    class Meta:
        unique_together = (('platform', 'dist_method'),)
        ordering = ['platform', 'dist_method']
        
# Series, Game content and Releases
class Series(models.Model):
    parent_series = models.ForeignKey('self', 
                                      blank=True, 
                                      null=True,
                                      related_name='subseries_set')
    name = models.CharField(max_length=50, unique=True)
    
    def __unicode__(self):
        return self.name
        
    class Meta:
        ordering = ['name']
        verbose_name_plural = 'series'

class Game(models.Model):
    series = models.ForeignKey(Series, blank=True, null=True)
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name
        
    class Meta:
        ordering = ['series', 'name']
        
class GameContent(models.Model):

    game = models.ForeignKey(Game,null=True)
    name = models.CharField(max_length=50,null=True)

    min_players = models.IntegerField(default=1)
    max_players = models.IntegerField(default=1)
    
    def __unicode__(self):
        return self.name
        
    class Meta:
        ordering = ['name', 'game']
        unique_together = (('name', 'game',),)

class Region(models.Model):
    slug = models.CharField(max_length=10, unique=True)
    name = models.CharField(max_length=50, unique=True)
    
    def __unicode__(self):
        return self.name
        
    class Meta:
        ordering = ['name']

class Release(models.Model):
    name = models.CharField(max_length=50)
    region = models.ForeignKey(Region)
    platform_distmethod = models.ForeignKey(PlatformDistMethod)
    release_date = models.DateField()
    boxart = models.ImageField(upload_to='vgdb/boxart')

#class ReleaseGame(models.Model):
#    release = models.ForeignKey(Release)
#    game = models.ForeignKey(Game)


frogohs/apps/vgdb/views.py
from django.shortcuts import render
from django.views.decorators.http import require_safe

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from models import Platform, \
                   DistMethod, \
                   Series, \
                   Game, \
                   GameContent

def template_name(request, model, view_type, ext = 'html'):
    return "%(app_name)s/%(model)s_%(view_type)s.%(ext)s" % \
               {'app_name': 'vgdb',
                'model': model.__name__.lower(),
                'view_type': view_type,
                'ext': ext}

def render_list(request, model, **kwargs):
    return render(request, 
                  template_name(request, model, 'list'),
                  kwargs)

def render_detail(request, model, **kwargs):
    return render(request, 
                  template_name(request, model, 'detail'),
                  kwargs)

@require_safe    
def platform_list_get(request):
    platform_list = Platform.objects.all()

    return render_list(request, Platform, platform_list=platform_list)

@require_safe
def platform_detail_get(request, platform_slug):
    platform = Platform.objects.get(slug=platform_slug)

    return render_detail(request, Platform, platform=platform)
       
@require_safe
def distmethod_list_get(request):
    distmethod_list = DistMethod.objects.all()

    return render_list(request, DistMethod, distmethod_list=distmethod_list)

@require_safe
def distmethod_detail_get(request, distmethod_slug):
    distmethod = DistMethod.objects.get(slug=distmethod_slug)

    return render_detail(request, DistMethod, distmethod=distmethod)

@require_safe
def series_list_get(request):
    series_list = Series.objects.all()

    return render_list(request, Series, series_list=series_list)

@require_safe
def series_detail_get(request, series_id):
    series = Series.objects.get(pk=series_id)

    return render_detail(request, Series, series=series)

@require_safe
def game_detail_get(request, game_id):
    game = Game.objects.get(pk=game_id)

    return render_detail(request, Game, game=game)
    

frogohs/apps/vgdb/templates/vgdb/distmethod_detail.html
{% extends "base.html" %}

{% block title %}
    Distribution Method Detail
{% endblock %}

{% block content %}
    <h1>{{distmethod.name}}</h1>
    
    <h2>Platforms</h2>
    
    <ul>
    {% for rel in distmethod.platform_set.all %}
        <li>
            <a href="{% url vgdb-platform-detail platform_slug=rel.platform.slug %}"
            >
            {{ rel.platform.name }}
            </a>
        </li>
    {% endfor %}
    </ul>
    
{% endblock %}

frogohs/apps/vgdb/templates/vgdb/distmethod_list.html
{% extends "base.html" %}

{% block title %}
    Distribution Method List
{% endblock %}

{% block content %}
    <h1>Distribution Method List</h1>
    <ul>
    {% for dist_method in distmethod_list %}
        <li>
            <a href="{% url vgdb-distmethod-detail distmethod_slug=dist_method.slug %}">
                {{dist_method.name}}
            </a>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

frogohs/apps/vgdb/templates/vgdb/game_detail.html
{% extends "base.html" %}

{% block title %}
    Game Detail
{% endblock %}

{% block content %}
    <h1>{{game.name}}</h1>
    
    {% if game.series %}
    <h2>Series:</h2>
    
    <a href="{% url vgdb-series-detail series_id=game.series.id %}">
        {{game.series.name}}
    </a>
    {% endif %}

    <h2>Content</h2>
    <ul>
    {% for gamecontent in game.gamecontent_set.all %}
    <li>{{gamecontent.name}}</li>
    {% endfor %}
    </ul>
    
{% endblock %}

frogohs/apps/vgdb/templates/vgdb/platform_detail.html
{% extends "base.html" %}

{% block title %}
    Platform Detail
{% endblock %}

{% block content %}
    <h1>{{platform.name}}</h1>
    
    <img alt="{{platform.name}} logo" 
        src="/static/img/platform-logo-{{platform.slug}}.svg" 
        />
        
    <h2>Distribution Methods</h2>
    
    <ul>
    {% for rel in platform.dist_method_set.all %}
        <li>
            <a href="{% url vgdb-distmethod-detail distmethod_slug=rel.dist_method.slug %}"
            >
            {{ rel.dist_method.name }}
            </a>
        </li>
    {% endfor %}
    </ul>
    
{% endblock %}

frogohs/apps/vgdb/templates/vgdb/platform_list.html
{% extends "base.html" %}

{% block title %}
    Platform List
{% endblock %}

{% block content %}
    <h1>Platform List</h1>
    <ul>
    {% for platform in platform_list %}
        <li>
            <a href="{% url vgdb-platform-detail platform_slug=platform.slug %}">
                {{platform.name}}
            </a>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

frogohs/apps/vgdb/templates/vgdb/series_detail.html
{% extends "base.html" %}

{% block title %}
    Series Detail
{% endblock %}

{% block content %}    
    <h1>{{series.name}}</h1>
    
    {% if series.parent_series %}
        <h2>Parent Series: <a href="{% url vgdb-series-detail series_id=series.parent_series.id %}"
            >
            {{ series.parent_series.name }}
            </a></h2>
    {% endif %}    
    
    {% with subseries_list=series.subseries_set.all %}    
    {% if subseries_list %}
    <h2>Sub-series</h2>
    <ul>
    {% for subseries in subseries_list %}
        <li>
            <a href="{% url vgdb-series-detail series_id=subseries.id %}"
            >
            {{ subseries.name }}
            </a>
        </li>
    {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
    
    <h2>Games</h2>
    <ul>
    {% for game in series.game_set.all %}
        <li>
            <a href="{% url vgdb-game-detail game_id=game.id %}">
                {{game.name}}
            </a>
        </li>
    {% endfor %}
    </ul>
    
{% endblock %}

frogohs/apps/vgdb/templates/vgdb/series_list.html
{% extends "base.html" %}

{% block title %}
    Series List
{% endblock %}

{% block content %}
    <h1>Series List</h1>
    <ul>
    {% for series in series_list %}
        <li>
            <a href="{% url vgdb-series-detail series_id=series.id %}">
                {{series.name}}
            </a>
        </li>
    {% endfor %}
    </ul>
{% endblock %}